/*
 * 15-11-2018: 
 * This idea and implementation was done by Pratyush and it worked fine in AdSalesUAT. Putting this back in all environments.
 * Writing this Dummy Class to cater Do Not For Process Builder. Refer to email chain about the issue of Changing Stage of An Opportunity from Closed Won to Confirmed / Awaiting Booking
 * Writing this Dummy Test Class for Code Coverage. Nothing to Assert.
*/
@isTest
public class AT_DummyClass_Test {
    
    @isTest
    public static void Unit01(){
        AT_DummyClass.doNothing(null);
    }
    
}