public interface CS_Questionnaire_Interface
{
	/*------------------------------------------------------------
	Author:			Mike Jupp
	Company:		CloudSense
	Description:	Interface class for Advanced Flow Manager
	History
	<Date>		<Authors Name>		<Brief Description of Change>
	Sep 18		Mike Jupp			Created
    ------------------------------------------------------------*/
	
	// Questionnaire interface
	CS_Interface_Utilities.Response process(CS_Interface_Utilities.Request req);
}