public class News_TriggerHelper {
      public static Boolean OpportunityManagement_After_Update_Executing = false;
      public static Boolean OpportunityManagement_Before_Update_Executing = false;


/*
   //Used for testing purposes
   public static Boolean falseFlag = false;

    public static Boolean OpportunityManagement_After_Update_Executing {
        get { return falseFlag;}
        set {OpportunityManagement_After_Update_Executing = value;}
    }

    public static Boolean OpportunityManagement_Before_Update_Executing {
        get { return falseFlag;}
        set {OpportunityManagement_Before_Update_Executing = value;}
    }*/

}