/**
* @author       Kamal Sharma
* @date         2018-05-25
* @className	NXX2_AppConstants
* @description  This class have contacts defined which will be used by other NXX2_* classes.
*/
public class NXX2_AppConstants {
    public static final String STATIC_RESOURCE_NAME_SOCIAL_AD_TYPE = 'NXX2_SocialAdType';
    public static final String STATIC_RESOURCE_NAME_SOCIAL_AD_CREATIVE_TYPE = 'NXX2_SocialAdCreativeType';
    
    public static final String TAB_WITH_NEWLINE = '\r\n';
    public static final String BOUNDARY = '----------9889464542212';
    public static final String DELIMITER = '\r\n--' + BOUNDARY + '\r\n';
    public static final String CLOSE_DELIM = '\r\n--' + BOUNDARY + '--';
    public static final String FILE_DELIMITER =':file:';
}